# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="runsession",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runsession",
            name="max_speed_mps",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="runsession",
            name="suspicious_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="runsession",
            name="trust_score_snapshot",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="runsession",
            name="validation_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="runsession",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("valid", "Valid"),
                    ("suspicious", "Suspicious"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="accuracy_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="altitude_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="client_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="heading_degrees",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="mock_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="speed_mps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="validation_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="UserTrustProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(db_index=True, default=100)),
                ("suspicious_runs", models.PositiveIntegerField(default=0)),
                ("rejected_runs", models.PositiveIntegerField(default=0)),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("app_version", models.CharField(blank=True, max_length=64)),
                (
                    "device_id_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("is_emulator", models.BooleanField(default=False)),
                ("is_mock_location", models.BooleanField(default=False)),
                ("developer_mode", models.BooleanField(default=False)),
                ("integrity_level", models.CharField(blank=True, max_length=32)),
                ("signals", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_signals",
                        to="api.runsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunValidationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                ("score_delta", models.IntegerField(default=0)),
                ("message", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_events",
                        to="api.locationpoint",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_events",
                        to="api.runsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
